name: build
on:
  pull_request: {}
jobs:
  generate-matrix:
    runs-on: ubuntu-latest
    outputs:
      matrix: ${{ steps.set-matrix.outputs.matrix}}
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Install dependencies
        run: |
          sudo apt update
          sudo apt install -y make jq
          wget https://github.com/mikefarah/yq/releases/download/v4.20.1/yq_linux_amd64 -O yq
          chmod +x yq
          sudo chown root:root yq
          sudo mv yq /usr/bin/yq

      - id: set-matrix
        run: |
          echo "::set-output name=matrix::{\"image\": $(make images-json)}"

  build-docker-image:
    needs: generate-matrix
    runs-on: ubuntu-latest
    strategy:
      matrix: ${{ fromJSON(needs.generate-matrix.outputs.matrix) }}
    steps:
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
        with:
          config-inline: |
            [worker.oci]
              max-parallelism = 1

      - name: Checkout
        uses: actions/checkout@v2

      - name: Install dependencies
        run: |
          sudo apt update
          sudo apt install -y make
          wget https://github.com/mikefarah/yq/releases/download/v4.20.1/yq_linux_amd64 -O yq
          chmod +x yq
          sudo chown root:root yq
          sudo mv yq /usr/bin/yq

      - name: Make build image ${{ matrix.image }}
        run: |
          IMAGES=${{ matrix.image }} make build
